# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - beeboyv3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://beeboyv3registre.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2d764613314b4caaaf6f321c4c0ea2ec }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c5b65ac0c4c540f6ad09e360a8852ae9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: beeboyv3registre.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d764613314b4caaaf6f321c4c0ea2ec }}/imagebeeboyv3:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'beeboyv3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1bdda32680294f6fbd9531204d1afa66 }}
        images: 'beeboyv3registre.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d764613314b4caaaf6f321c4c0ea2ec }}/imagebeeboyv3:${{ github.sha }}'